imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: 'force'
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    param_fetcher_listener: true
    exception:
        enabled: true
        exception_controller: 'AppBundle\Controller\ExceptionController::showAction'
    serializer:
        groups: ['Default']
    versioning:
        enabled: true
        default_version: '1.0'
        resolvers:
            query: true
            custom_header: true
            media_type:
                enabled: true
        guessing_order:
            - media_type
            - custom_header
            - query
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json }

sensio_framework_extra:
    view:
        annotations: true
    request:
        converters: true

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path: '%jwt_public_key_path%'
    pass_phrase: '%jwt_key_pass_phrase%'
    token_ttl: '%jwt_token_ttl%'

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['X-Accept-Version']
            allow_methods: ['POST', 'PATCH', 'GET', 'DELETE']
            max_age: 1

fos_http_cache:
    proxy_client:
        symfony:
            http:
                servers:
                    - movies.local
                base_url: movies.local/app_dev.php
    cache_control:
        defaults:
            overwrite: false
        rules:
            -
                match:
                    path: ^/
                headers:
                    cache_control:
                        public: true
                        max_age: 1
                        s_maxage: 1
                    vary: [X-Accept-Version, Accept]
                    etag: false

nelmio_api_doc:
    routes:
        path_patterns:
            - ^/movie
            - ^/human
            - ^/user
    models:
        use_jms: true
    documentation:
        info:
            title: "Movies API"
            description: "Movies database API"
            version: 1.0.0
        parameters:
            param_movie_id:
                name: movie
                in: path
                type: integer
                description: "Movie id"
                required: true