movies:
    type: rest
    resource: AppBundle\Controller\MoviesController

movies_post:
    path: /movies
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\MoviesController:postMoviesAction
        _format: json

movies_patch:
    path: /movies/{movie}
    methods: [PATCH]
    defaults:
        _controller: AppBundle\Controller\MoviesController:patchMovieAction
        _format: json

humans:
    type: rest
    resource: AppBundle\Controller\HumansController

humans_post:
    path: /humans
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\HumansController:postHumansAction
        _format: json

movies_roles_post:
    path: /movies/{movie}/roles
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\MoviesController:postMovieRolesAction
        _format: json

users:
    resource: AppBundle\Controller\UsersController
    type: rest

users_post:
    path: /users
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\UsersController:postUserAction
        _format: json

users_patch:
    path: /users/{theUser}
    methods: [PATCH]
    defaults:
        _controller: AppBundle\Controller\UsersController:patchUserAction
        _format: json

tokens:
    resource: AppBundle\Controller\TokensController
    type: rest

images:
    resource: AppBundle\Controller\ImagesController
    type: rest

images_post:
    path: /images
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\ImagesController:postImagesAction
        _format: json

images_upload_put:
    path: /images/{image}/upload
    methods: [PUT]
    defaults:
        _controller: AppBundle\Controller\ImagesController:putImageUploadAction

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc